---
title: "Datasets"
output:
  rmdformats::robobook:
    highlight: kate
---


```{r}
# git config --global --unset user.name
# git config --global --unset user.email
```


```{r}
usethis::use_git_config(
  scope = "project",
  user.name = "juanchiem",
  user.email = "edwardsmolina@gmail.com"
)
credentials::set_github_pat("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")
```

```{r}
gitcreds::gitcreds_set()

```

```{r echo=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r eval=FALSE}
pacman::p_load(tidyverse, googlesheets4, janitor)
gs4_auth(email = "edwardsmolina@gmail.com")
gs4_deauth()
datasets <- gs4_get("https://docs.google.com/spreadsheets/d/16FUAtd-u50sU2si0Ot7j9Ueou7qwlGt5t9NkAdKwlBM/edit?usp=sharing")
```

```{r eval=FALSE}
olivo <- read_sheet(datasets, sheet = "olivo", 
                    guess_max = 10000, skip=0) 
```

```{r eval=FALSE}
soja <- read_sheet(datasets, sheet = "soja", 
                    guess_max = 10000, skip=0) 
```

```{r}
canola <- read_sheet(datasets, sheet = "canola", 
                    guess_max = 10000, skip=0) %>% 
  janitor::clean_names() 
```

```{r}
cebada <- read_sheet(datasets, sheet = "cebada", 
                    guess_max = 10000, skip=0) %>% 
  janitor::clean_names() 
```

```{r}
poroto <- read_sheet(datasets, sheet = "poroto", guess_max = 10000, skip=0)
```

```{r}
save(olivo, soja, canola, cebada, poroto, file="data/data.RData")
```
