
```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      eval=FALSE, 
                      fig.width = 12, 
                      fig.height = 8)
options(width = 90)
```

```{r, include=FALSE}
pacman::p_load(tidyverse, emmeans)
load("data/data.RData")
```

# DSI 

Disease severity index (Indice de severidad)

* Poroto/sclerotinia 

```{r}
poroto
```
 
Dataset de formato wide, que incluye 3 variables descriptivas y 4 variables respuesta. 

```{r}
poroto %>% 
  mutate(diseased = rowSums(dplyr::select(., matches('1|2|3|4')))) %>% 
  mutate(inc = diseased/n*100) %>% 
  mutate(dsi_eq1 = (1*class_1+2*class_2+3*class_3+4*class_4)/(n*4) *100) %>% 
  mutate(dsi_eq2 = (1*class_1+2*class_2+3*class_3+4*class_4)/n) %>% 
  mutate(dsi_midpoint = (.13*class_1 +.375*class_2 + .625*class_3 + .875*class_4)/n*100)%>% 
  mutate_at(vars(trt, rep), as.factor) -> poroto_dsi
```

Print 

```{r}
poroto_dsi
```

Model fitting 

```{r}
mod0 <- lm(dsi_midpoint ~ trt, data = poroto_dsi)
par(mfrow = c(1, 2))
plot(mod0, which = c(1,2))
```

```{r}
layout(1)
MASS::boxcox(mod0)
locator()
# plot(fitted(mod0), resid(mod0), xlab = "Fitted", ylab = "Residuals")
# abline(h = 0, lty = 2, col = "darkorange", lwd = 2)
# plot(mod0, which = c(1))
```

```{r}
mod1 <- lm(sqrt(dsi_midpoint) ~ trt, data = poroto_dsi)
par(mfrow = c(1, 2))
plot(mod1, which = c(1,2))
MASS::boxcox(mod1)
```

```{r}
bctran <- make.tran("boxcox", 0.596)
mod2 <- with(bctran,
            lm(linkfun(dsi_midpoint) ~ trt, data = poroto_dsi))
par(mfrow = c(1, 2))
plot(mod2, which = c(1,2))
```

```{r}
asin_tran <- make.tran("asin.sqrt", 100)
mod3 <- with(asin_tran,
            lm(linkfun(dsi_midpoint) ~ trt, data = poroto_dsi)
            )
par(mfrow = c(1, 2))
plot(mod3, which = c(1,2))
emmeans(mod3, ~ trt, type = "response")

```


```{r}
poroto_dsi_p = transform(poroto_dsi, p = (dsi_midpoint/100))

mod4 = lm(log(p/(1-p)) ~ trt, data = poroto_dsi_p)
emmeans(mod4, ~trt, 
        tran = "logit", at = list(dsi_midpoint = 3:81), 
        type = "response")
```

```{r}
AIC(mod1, mod2, mod3, mod4)
```

