```{r}
library(tidyverse)
```

```{r}
# Definición matemática de los modelos logistico, gompertz e monomolecular
lo <- function(x, K, y0, r) {K/(1+((K-y0)/y0)*exp(-r*x))}
```

Establezcamos el periodo critico

```{r}
plot_base <- ggplot(data = data.frame(t = 0), aes(x = t))+
  annotate("rect", xmin = 20, xmax = 40, 
           ymin = 0, ymax = 100,
           alpha = .2)+
  labs(y="Incidencia %")+
  xlim(0,40) + 
  theme_minimal()+
  scale_y_continuous(limits = c(0,100),
                     breaks = scales::pretty_breaks(5))
plot_base

```

Curva logistica de referencia de manchas sin intervencion r =.5

```{r}
param_ref = list(K=70, y0=0.01, r=.5)

plot_base +  
  stat_function(fun = lo, args=param_ref, col="red") 

ggsave(last_plot(), file = "curva_ref.png", w=6, h=4)
```

Efecto cultivar

```{r}
param_montoya = list(K=60, y0=0.01, r=.3)

plot_base +  
  stat_function(fun = lo, args=param_ref, col="red") +
  stat_function(fun = lo, args=param_montoya, col="blue") 

# ggsave(last_plot(), file = "resistencia.png", w=6, h=4, dpi=600, scale = .8)
```

Efecto ambiente

```{r}
# param_ref = list(K=60, y0=0.01, r=.5)
param_lluvioso = list(K=70, y0=0.01, r=.6)
param_seco = list(K=60, y0=0.01, r=.2)

plot_base +  
  # stat_function(fun = lo, args=param_ref, col="blue") +
  stat_function(fun = lo, args=param_lluvioso, col="red")+ 
  stat_function(fun = lo, args=param_seco, col="green") 

ggsave(last_plot(), file = "ambiente.png", 
              w=6, h=4, dpi=600, scale = .8)

```

Aplicamos un fungicida mezcla triazoles y disminuimos la tasa de progreso a .3

```{r}
param_fungicida1 = list(K=60, y0=0.01, r=.3)
param_fungicida2 = list(K=60, y0=0.01, r=.2)

plot_base +  
  stat_function(fun = lo, args=param_ref, col="red") +
  stat_function(fun = lo, args=param_fungicida1, col="blue") +
  stat_function(fun = lo, args=param_fungicida2, col="green") 

ggsave(last_plot(), file = "fungicidas.png", 
       w=6, h=4, dpi=600, scale = .8)
```

Aplicamos un fungicida mezcla triple y disminuimos la tasa de progreso a .2

```{r}
param_fungicida2 = list(K=60, y0=0.01, r=.2)

plot_base +  
  stat_function(fun = lo, args=param_ref, col="red") +
  stat_function(fun = lo, args=param_fungicida1, col="blue") 

ggsave(last_plot(), file = "curva_mezcla.png", 
       w=6, h=4, dpi=600, scale = .8)
```